name: 欢迎
email: 2693532573@qq.com
url: url
#description: "A blog and a portfolio"
author: "CQQ"
title: "以文会友，以友辅仁"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
#github:
 # username: username

#twitter:
 # username: username
